name: CI

on:
  pull_request: &paths
    paths:
      - '*.yaml'
      - '.github/workflows/ci.yml'
  push: *paths
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  ci:
    name: Building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: ESPHome Build
        uses: esphome/build-action@f0a331817f5535854a10a42621b6a8b7ebe95c4c  # v7.2.0
        with:
          yaml-file: snuffelaar.yaml
          esphome-version: 2026.5.0
      - name: ESPHome Build (Factory)
        uses: esphome/build-action@f0a331817f5535854a10a42621b6a8b7ebe95c4c  # v7.2.0
        with:
          yaml-file: snuffelaar.factory.yaml
          esphome-version: 2026.5.0
