name: CI

on:
  pull_request: &paths
    paths:
      - '*.yaml'
      - '.github/workflows/ci.yml'
  push: *paths
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  ci:
    name: Building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: ESPHome Build
        uses: esphome/build-action@ae5408cdbc4f70692bf8e345c4982bca05a93667  # v8.1.0
        with:
          yaml-file: snuffelaar-esp32.yaml
          version: 2026.5.1 #esphome-version
      - name: ESPHome Build (Factory)
        uses: esphome/build-action@ae5408cdbc4f70692bf8e345c4982bca05a93667  # v8.1.0
        with:
          yaml-file: snuffelaar-esp32.factory.yaml
          version: 2026.5.1 #esphome-version
